<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit150629d4956ebf44d79dd210dd9b7bee
{
    public static $files = [
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
    ];

    public static $prefixLengthsPsr4 = [
        'P' =>
            [
                'Psr\\Http\\Message\\' => 17,
            ],
        'G' =>
            [
                'GuzzleHttp\\Psr7\\' => 16,
                'GuzzleHttp\\Promise\\' => 19,
                'GuzzleHttp\\' => 11,
            ],
    ];

    public static $prefixDirsPsr4 = [
        'Psr\\Http\\Message\\' =>
            [
                0 => __DIR__ . '/..' . '/psr/http-message/src',
            ],
        'GuzzleHttp\\Psr7\\' =>
            [
                0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
            ],
        'GuzzleHttp\\Promise\\' =>
            [
                0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
            ],
        'GuzzleHttp\\' =>
            [
                0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
            ],
    ];

    public static $prefixesPsr0 = [
        'Y' =>
            [
                'Yandex\\Tests' =>
                    [
                        0 => __DIR__ . '/..' . '/nixsolutions/yandex-php-library/tests',
                    ],
                'Yandex' =>
                    [
                        0 => __DIR__ . '/..' . '/nixsolutions/yandex-php-library/src',
                    ],
            ],
    ];

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit150629d4956ebf44d79dd210dd9b7bee::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit150629d4956ebf44d79dd210dd9b7bee::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit150629d4956ebf44d79dd210dd9b7bee::$prefixesPsr0;
        }, null, ClassLoader::class);
    }
}
