<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'Yandex\\Tests' => [$vendorDir . '/nixsolutions/yandex-php-library/tests'],
    'Yandex' => [$vendorDir . '/nixsolutions/yandex-php-library/src'],
];
